PRAGMA foreign_keys = ON;
.headers on
.mode box

-- (1)
SELECT NOME, SALARIO, SALARIO + SALARIO * 0.05 AS SALARIO_REAJUSTADO
FROM FUNCIONARIO;

-- (2)
SELECT NOME, SALARIO FROM FUNCIONARIO
WHERE SALARIO BETWEEN 4000 AND 6000
ORDER BY SALARIO ASC;

-- (3)
SELECT CPF FROM TRABALHA_EM
WHERE HORAS > 10 AND PROJNUMERO IN (1, 2, 3);

-- (4)
SELECT DISTINCT PROJLOCAL FROM PROJETO;

-- (5)
SELECT NOME, DATA_NASC FROM FUNCIONARIO
WHERE NOME LIKE 'A%';